@startuml
autonumber
actor Pårørende as parorende
participant System as system
database Database as db

activate parorende
parorende -> system: Oppretter avtale (dato, beskjed)
activate system
system -> db: Lagrer avtale
activate db
db --> system: Bekrefter avtale lagret
deactivate db
system --> parorende: Avtale lagret bekreftelse
deactivate system
deactivate parorende
@enduml
