@startuml
'autonumber

actor Pårørende as parorende
participant System as system
database Database as db

parorende -> system: Oppretter beskjed
activate system
system -> db: Lagrer beskjed
activate db
db --> system: Bekreftelse på lagring
deactivate db
system --> parorende: Beskjed lagret
deactivate system

@enduml
