@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor pleietrengende
participant System as system
database Database as db

pleietrengende -> system: Oppretter handleliste

system -> db: Lagrer handleliste
activate system

activate db
db --> system: Bekreftelse på lagring
deactivate system
deactivate db


pleietrengende -> system: Forspør handleliste
activate pleietrengende
system -> db: Henter handleliste
activate system
activate db
db --> system: Returnerer handleliste
deactivate db
system --> pleietrengende: Viser handleliste
deactivate system
deactivate pleietrengende


@enduml